{% set version = '0.9.6' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-jmv
  version: {{ version|replace("-", "_") }}

source:
  fn: jmv_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/jmv_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/jmv/jmv_{{ version }}.tar.gz
  sha256: 1718cbab4e37f9028bd9655985c3ba3a2c5123b1110d41bd86880cf3b8a12682

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1000
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-jmvcore >=0.9.5.2
    - r-r6
    - r-car >=3.0.0
    - r-multcomp
    - r-ggplot2 >=2.2.1
    - r-pmcmr
    - r-emmeans >=1.1.3
    - r-vcd
    - r-vcdextra
    - r-ggally
    - r-bayesfactor
    - r-psych >=1.7.5
    - r-gparotation
    - r-afex >=0.20.2
    - r-mvnormtest
    - r-lavaan
    - r-ggridges
    - r-rocr
    - r-nnet
    - r-mass
  run:
    - r-base
    - r-jmvcore >=0.9.5.2
    - r-r6
    - r-car >=3.0.0
    - r-multcomp
    - r-ggplot2 >=2.2.1
    - r-pmcmr
    - r-emmeans >=1.1.3
    - r-vcd
    - r-vcdextra
    - r-ggally
    - r-bayesfactor
    - r-psych >=1.7.5
    - r-gparotation
    - r-afex >=0.20.2
    - r-mvnormtest
    - r-lavaan
    - r-ggridges
    - r-rocr
    - r-nnet
    - r-mass

test:
  commands:
    - $R -e "library('jmv')"           # [not win]
    - "\"%R%\" -e \"library('jmv')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=jmv
  license: GPL (>= 2)
  summary: A suite of common statistical methods such as descriptives, t-tests, ANOVAs, regression,
    correlation matrices, proportion tests, contingency tables, and factor analysis.
    This package is also useable from the 'jamovi' statistical spreadsheet (see <https://www.jamovi.org>
    for more information).
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
