{% set version = '0.9.6.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-jmv
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/jmv_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/jmv/jmv_{{ version }}.tar.gz
  sha256: 18d44078f5d01a6def94e05e32f120483ea612dae458b1b998882c5e02496581

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-bayesfactor
    - r-ggally
    - r-gparotation
    - r-mass
    - r-pmcmr
    - r-r6
    - r-rocr
    - r-afex >=0.20.2
    - r-car >=3.0.0
    - r-emmeans >=1.1.3
    - r-ggplot2 >=2.2.1
    - r-ggridges
    - r-jmvcore >=0.9.5.2
    - r-lavaan
    - r-multcomp
    - r-mvnormtest
    - r-nnet
    - r-psych >=1.7.5
    - r-vcd
    - r-vcdextra
  run:
    - r-base
    - r-bayesfactor
    - r-ggally
    - r-gparotation
    - r-mass
    - r-pmcmr
    - r-r6
    - r-rocr
    - r-afex >=0.20.2
    - r-car >=3.0.0
    - r-emmeans >=1.1.3
    - r-ggplot2 >=2.2.1
    - r-ggridges
    - r-jmvcore >=0.9.5.2
    - r-lavaan
    - r-multcomp
    - r-mvnormtest
    - r-nnet
    - r-psych >=1.7.5
    - r-vcd
    - r-vcdextra

test:
  commands:
    - $R -e "library('jmv')"           # [not win]
    - "\"%R%\" -e \"library('jmv')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=jmv
  license: GPL (>= 2)
  summary: A suite of common statistical methods such as descriptives, t-tests, ANOVAs, regression,
    correlation matrices, proportion tests, contingency tables, and factor analysis.
    This package is also useable from the 'jamovi' statistical spreadsheet (see <https://www.jamovi.org>
    for more information).
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: jmv
# Type: Package
# Title: The 'jamovi' Analyses
# Version: 0.9.6.1
# Date: 2018-12-11
# Author: Ravi Selker, Jonathon Love, Damian Dropmann
# Maintainer: Jonathon Love <jon@thon.cc>
# Description: A suite of common statistical methods such as descriptives, t-tests, ANOVAs, regression, correlation matrices, proportion tests, contingency tables, and factor analysis. This package is also useable from the 'jamovi' statistical spreadsheet (see <https://www.jamovi.org> for more information).
# License: GPL (>= 2)
# Depends: R (>= 3.2)
# Imports: jmvcore (>= 0.9.5.2), R6, car (>= 3.0.0), multcomp, ggplot2 (>= 2.2.1), PMCMR, emmeans (>= 1.1.3), vcd, vcdExtra, GGally, BayesFactor, psych (>= 1.7.5), GPArotation, afex (>= 0.20.2), mvnormtest, lavaan, ggridges, ROCR, nnet, MASS
# Suggests: exact2x2, testthat, semPlot, carData, knitr, rmarkdown
# Encoding: UTF-8
# RoxygenNote: 6.1.1
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-04-21 09:33:01 UTC; ripley
# Repository: CRAN
# Date/Publication: 2019-04-22 06:58:25 UTC
