{% set version = "2.5.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-jmv
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/jmv_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/jmv/jmv_{{ version }}.tar.gz
  sha256: 350c0fc6a63420808bbcb8c24c09881211d8cbac8d798e6e88df54c3d0d42835

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-bayesfactor
    - r-ggally
    - r-gparotation
    - r-mass
    - r-pmcmr
    - r-r6
    - r-rocr
    - r-afex >=0.28_0
    - r-car >=3.0.0
    - r-dplyr
    - r-emmeans >=1.4.2
    - r-ggplot2 >=2.2.1
    - r-ggrepel
    - r-ggridges
    - r-jmvcore >=2.3.4
    - r-lavaan
    - r-magrittr
    - r-multcomp
    - r-mvnormtest
    - r-nnet
    - r-psych >=1.7.5
    - r-vcd
    - r-vcdextra
  run:
    - r-base
    - r-bayesfactor
    - r-ggally
    - r-gparotation
    - r-mass
    - r-pmcmr
    - r-r6
    - r-rocr
    - r-afex >=0.28_0
    - r-car >=3.0.0
    - r-dplyr
    - r-emmeans >=1.4.2
    - r-ggplot2 >=2.2.1
    - r-ggrepel
    - r-ggridges
    - r-jmvcore >=2.3.4
    - r-lavaan
    - r-magrittr
    - r-multcomp
    - r-mvnormtest
    - r-nnet
    - r-psych >=1.7.5
    - r-vcd
    - r-vcdextra

test:
  commands:
    - $R -e "library('jmv')"           # [not win]
    - "\"%R%\" -e \"library('jmv')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=jmv
  license: GPL-2.0-or-later
  summary: A suite of common statistical methods such as descriptives, t-tests, ANOVAs, regression, correlation matrices, proportion tests, contingency tables, and factor analysis. This package is also useable from the 'jamovi' statistical spreadsheet (see <https://www.jamovi.org> for more information).
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: jmv
# Type: Package
# Title: The 'jamovi' Analyses
# Version: 1.0.8
# Date: 2019-10-21
# Author: Ravi Selker, Jonathon Love, Damian Dropmann
# Maintainer: Jonathon Love <jon@thon.cc>
# Description: A suite of common statistical methods such as descriptives, t-tests, ANOVAs, regression, correlation matrices, proportion tests, contingency tables, and factor analysis. This package is also useable from the 'jamovi' statistical spreadsheet (see <https://www.jamovi.org> for more information).
# License: GPL (>= 2)
# Depends: R (>= 3.2)
# Imports: jmvcore (>= 1.0.8), R6, car (>= 3.0.0), multcomp, ggplot2 (>= 2.2.1), PMCMR, emmeans (>= 1.1.3), vcd, vcdExtra, GGally, BayesFactor, psych (>= 1.7.5), GPArotation, afex (>= 0.20.2), mvnormtest, lavaan, ggridges, ROCR, nnet, MASS
# Suggests: exact2x2, testthat, semPlot, carData, knitr
# Encoding: UTF-8
# RoxygenNote: 6.1.1
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-10-21 11:43:45 UTC; jonathon
# Repository: CRAN
# Date/Publication: 2019-10-23 23:50:02 UTC
