# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1
    - CONFIG=osx_r_base3.5.1

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "TVx3y/RdL5i7lZm9e+stHnhSVdC2nJib1EaBMh8hzs8Zs32G0AHPuz5GUIbgzjuzS+qkeYtXRK3ye5zxQrq9X8RafRdrokRdzA5loFh6erXNIN73naaa0SGYN9NeyHEOdEU0e+YHIJzivWVOui6m/xGCxh+0LoJRUpmFE7Sz+PzbS9V5oKESeMpTsWh9VjQ5ySg+52r5IBP0+SG4pWMut+SUlxcZTJ9ZPffB9Bh1Kd/Xzod26VDJcVTB2gr47JrX1NjYVYSU+NMa/dfPlzbTesuCTt9LmvkC3WdjcGY0vnlfQmW7pxLhS7pouLn4aXgnXplXkwA1ihNldLJfX1whB5YwwRKX0bM921w7OBtXiRCTy2CAH91ml7pzWPtx7Lb58rlPSNEjScbMeqmz0Oy8jgeAHOODBlX++q1Pqy5ghp18UAoDnb4T5gav31H1+pgPswJsAZ1T06UEhljJkFF7SXRowwfrMKxfpMxcd5kwMS/fYlk0b2aaxbX/hcooHauUz6mFLc3rhrkf6yTPECFFAfuO9yBoF/G7wtXJzfc4oCKEA8vBVAdpUCpNzrCpeu6MQ2bAWPPhd5MZPdXSJTrN2aVMmMpnWDv4AJOlTcT0awP99dELDZAnZa1B0vJS/g/2ohrP9EdzL+wOGBtG+fUQrvwkFibqWdBKwlAv/Bf/Aik="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
