travis:
  secure:
    BINSTAR_TOKEN: WLNWi//3Ss4ONsu5NBppPo/1yEA3VTDQ7LotRVHpXT38a8Hfu3M0AjuVqp+eF+QyQN7b398INeQivt2qHlAmX3IO4LmMqKmn90rcQUKs6ENIlp2mm0nT+/HKiS3MdRPrkZIOZ70IVuZBe+D/q74ifPAjhztIrwqSqzgixVh5mFTV8xdr/D8vJaDDgKTuF2RJ2NgktUMH6aPIygunmTAOqKljyXwRb32vGYg5L/flOWl5fxW91Sz3k3S6A5E5GaoN1LC20Y7+yqpBss3Oi/l/SElHxvG7nl68ECX9xf6yQj9SxN3ZX4aP03I9RymRx7na+s1ltgM2MXZaziBnnGKHNNAnqaCzpj/Fnf//KaJVS+F17R6oigo5XajOtBQ6MwFPuBz9VstssOH9YbfzFgoIOqWgnk7+BT5pz9hMgh2ccsXyYcbYjkxTIm7qmYyxRZmXIRcmTGSq0pmKl6yF3y41NjmaTq48Pe59gcXS3Mu5XkaqIunze1PwnXl0ab1Sk/heUSJtErA6wIXaVDo7ju52CIXG6RWHsOyHIY45FbVCUQOpaehq/kyZlwiqdZ/XEqZbuZhh5LKPtAFk29jHtfKhgxJ4RdM6hhPLFKgcWAzfsiO9MqBTFjf5E9XqX5Di3e2z8XoHlu8/WecAYv2ex2eki1Ds0LV/eDUMfzm3K5DDQA0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
