travis:
  secure:
    BINSTAR_TOKEN: UGl3NSj/PW1Tm2phG088pJpEGLoTcBWq1FYOHLjuplYKCnvkclxs2mrZf+HBXJ2kSqPa8LtKkrOSwUQD/z+SQVjjiy43WuAvNygrUqa3fgjInBNNHRkh4Tl3T4bNZT5gPYt0gYvbAadAPkCJR0XjY89b7m4lZOXvtAvFiYiKvlvdtWWVDU5a289QwSwH1gPtOVqd0SBTDiW9xrVA56XiXj3dHDgq7n9OkCZpVKbL7uzvMSz09JtP+IBlB3JuNcGnbhjCky8dqFpODjSV8RA7/vcGT84b6hGIJp61fWvhwKeuZwpe3ZJL9WuWPzfQUYN7WQ0J/Ijt/ti5FvL8ixhbp9LbJb1UE23TmL0gNE2RSSbvLFDjcYb4L6Ti3DLj3YNzQ4hfo+RyuzpVt+NByLJ/wwzdGgEVFJKX8jxBWbYMDfbCtPGlNCtwPyvC3bhbDkXZWuwdy11+ZNN4oMvOJKchcIHSqc8B35fgi+saV9S4/78fEI+C81aHuoWOIxhtceMPs2RRo8tBgERvzwS70LtwA9ZWXazB/c6cZqVq7g8+3UHb4be4nP9nC4wWQKhbs3KAnGm4Ngb/t2548y4O5oy1UV/5t9xpJnzDMHaGIgVprqSY0YTgaRN30YYbaH+XriN6r3b4KD1gC/z4U51rzC8zI6s+vtV91vPOX+LDNF7ugNg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
