appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: TVx3y/RdL5i7lZm9e+stHnhSVdC2nJib1EaBMh8hzs8Zs32G0AHPuz5GUIbgzjuzS+qkeYtXRK3ye5zxQrq9X8RafRdrokRdzA5loFh6erXNIN73naaa0SGYN9NeyHEOdEU0e+YHIJzivWVOui6m/xGCxh+0LoJRUpmFE7Sz+PzbS9V5oKESeMpTsWh9VjQ5ySg+52r5IBP0+SG4pWMut+SUlxcZTJ9ZPffB9Bh1Kd/Xzod26VDJcVTB2gr47JrX1NjYVYSU+NMa/dfPlzbTesuCTt9LmvkC3WdjcGY0vnlfQmW7pxLhS7pouLn4aXgnXplXkwA1ihNldLJfX1whB5YwwRKX0bM921w7OBtXiRCTy2CAH91ml7pzWPtx7Lb58rlPSNEjScbMeqmz0Oy8jgeAHOODBlX++q1Pqy5ghp18UAoDnb4T5gav31H1+pgPswJsAZ1T06UEhljJkFF7SXRowwfrMKxfpMxcd5kwMS/fYlk0b2aaxbX/hcooHauUz6mFLc3rhrkf6yTPECFFAfuO9yBoF/G7wtXJzfc4oCKEA8vBVAdpUCpNzrCpeu6MQ2bAWPPhd5MZPdXSJTrN2aVMmMpnWDv4AJOlTcT0awP99dELDZAnZa1B0vJS/g/2ohrP9EdzL+wOGBtG+fUQrvwkFibqWdBKwlAv/Bf/Aik=}
bot:
  automerge: true
